name: FCGS_env
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - lpips
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/freqencoder
    - submodules/gridencoder
    - submodules/gridcreater
    - submodules/arithmetic